name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Building project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup emscripten
        uses: mymindstorm/setup-emsdk@7
      - name: Verify
        run: emcc -v
      - name: Get latest CMake
        uses: lukka/get-cmake@latest 
      - name: Setup C++ environment
        uses: kurocha/setup-cpp@v1
      - name: Setup OpenGL
        uses: openrndr/setup-opengl@1.1
      - name: Give rights to cli
        run: chmod +x webppcli.sh
      - name: Build Emscripten
        run: ./webppcli.sh build